name: CI/CD to GCP VM with Docker Compose

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yourdockerhub/yourapp:${{ github.sha }}

      # - name: SSH to GCP VM and Deploy
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.GCP_VM_IP }}
      #     username: ${{ secrets.GCP_VM_USER }}
      #     key: ${{ secrets.GCP_VM_SSH_KEY }}
      #     script: |
      #       cd /srv/my-app
      #       docker-compose pull
      #       docker-compose up -d --remove-orphans
